# Generated by Django 5.2.4 on 2025-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
